### ISSUE TITLE
Select an entity in the canvas to inspect it

### ISSUE THREAD

**Issue by arya-s** [suchipi/hex-engine#15]
I want to be able to use the mouse to click on an entity and open its particular entry in the inspector like I can inspect HTML elements with dev tools.

**Comment by arya-s** [comment]
Something like this: https://streamable.com/zkjf6

**Comment by suchipi** [comment]
I definitely want that too!

I think we should expand and focus the clicked Entity though, instead of replacing the root entity. I kind of like how little clutter there is in your approach, though. Do you have an opinion one way or the other?

I think what we should do to make this possible is:
* Add a "select entity" button to the inspector's `Controls` component that puts the inspector into "selecting mode"
  * All the icons the inspector uses come from the firefox debugger; they probably have one for "select element" that we can use: https://dxr.mozilla.org/mozilla-central/source/devtools/client/debugger/images
* Export a hook function from the inspector package that has returns an object with functions on it that:
  * return whether the inspector is currently in "selecting mode" (`() => boolean`)
  * expand and focus an Entity, by instance (`(entity: Entity) => void`)
    * this would also end "selecting mode"
* Use that hook in 2d's `Geometry` component in conjunction with a `LowLevelMouse` to expand an Entity on click, but only when in "selecting mode"

Are you interested in contributing a PR that makes these changes? I can help you along the way.

**Comment by arya-s** [comment]
I was putting this together quickly so I didn't have the time to work on expanding the tree.

Your points are exactly how I envisioned it (mimicking dev tools).

Thanks for outlining the approach. The way I implemented it was quite hackish. I only added code to the inspector package which meant I had to wait for the entity to receive its Canvas component. Going the other way ans placing this directly in Geometry seems much easier!

Finally, yes I'd really like to contribute this!

**Comment by suchipi** [comment]
Turning the inspector into a browser extension is a non-goal of this project, since doing so would mean that users would have to go out of their way to add it. I want the inspector to be available to everyone, out-of-the-box (including people using mobile devices). So I don't think we need to worry about that.

I'm excited to hear you are interested in contributing! Let me know if there's anything I can do to help. You are welcome to open a PR while you're still working on it if you want, or you can wait until you feel it's done. Whatever you're more comfortable with.
